version: "3.7"
services:
  fenics:
    build: 
      context: ..
      dockerfile: ./docker/fenics/Dockerfile 
    working_dir: /home/fenics/work
    env_file: ./.env
    volumes: 
      - ..:/home/fenics/work
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
  pvs:
    build: ./pvs
    volumes:
      - ./results:/opt/paraview/share/paraview-5.6/data
    ports:
      - 8080:8080
    command: --port 8080 --content /opt/paraview/share/paraview-5.6/web/visualizer/www/ --data /opt/paraview/share/paraview-5.6/data
