version: "3.7"
services:
  mixed_dim:
    build: .
    working_dir: /home/fenics/mixed_dim
    volumes: 
      - .:/home/fenics/mixed_dim
      - ../shared:/home/fenics/mixed_dim/shared
    stdin_open: true
    tty: true
